name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    name: Build deploy python3.7 beginner
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  

  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
